name: "maestrogateway"
description: "MCZ Maestro Equipment Gateway with Mqtt / JSON"
version: "1.0.21"
slug: "maestrogateway"
url: https://github.com/hassio-addons/addon-example
image: ghcr.io/domhaas/maestrogateway-hassio
init: false
arch:
  - armv7
services:
  - mqtt:need
options:
  startup_wait: 10
  mcz_ip: "192.168.120.1"
  mcz_port: 81
  mqtt_host:
  mqtt_port: 1883
  mqtt_username:
  mqtt_password:
  mqtt_topic_sub: "Maestro/Command/"
  mqtt_topic_pub: "Maestro/"
  mqtt_payload_type: "TOPIC"
  log_level: "INFO"
schema:
  startup_wait: int
  mcz_ip: str
  mcz_port: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_topic_sub: str
  mqtt_topic_pub: str
  mqtt_payload_type: list(TOPIC|JSON)
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)
